### ISSUE TITLE
No source codes? Suspect! 不给原代码？

### ISSUE THREAD

**Issue by lche059** [liangxiwei/ore-mine-optimize-mac#2]
why no source codes bro?
这里可是github，钓鱼不是这么钓的 😂

**Comment by liangxiwei** [comment]
给啊，等几天吧，现在一天能搞好几百呢，你看历史记录的README就知道我添加了啥了，都币圈的挖矿的地址发个0.02就够了，就算泄密给我我也没用

lche059 ***@***.***> 于2024年4月11日周四 17:26写道：

**Comment by lche059** [comment]
一天好几百？编也不能这么编啊😂 
我教你，现在最牛的优化是Parallel keypairs, batching hashes, gpu support，原作者说的，细节决定成败😂

**Comment by liangxiwei** [comment]
> 一天好几百？编也不能这么编啊😂 我教你，现在最牛的优化是Parallel keypairs, batching hashes, gpu support，原作者说的，细节决定成败😂

作者算个屁，我一个电脑跑20多个帐号，两个电脑跑，你没看我那个地址吗，就是其中一个而已。
