### ISSUE TITLE
这个程序会偷币， 挖到的一半会转到另外一个地址

### ISSUE THREAD

**Issue by geilivableman** [liangxiwei/ore-mine-optimize-mac#4]
挖到的转了一半去这个地址 

8NnUbqB3nm1ygAbMqPKxM5m7yurPsR92ibAaieg4ymzf    

挖的越多亏的越多，真离谱

**Comment by lche059** [comment]
卧槽，你还真用啊
他的目的根本不是偷你挖的，那能有多少
但是要是有人用大号挖。。。😂

**Comment by liangxiwei** [comment]
s*才会用大号挖,这个就是要分我一半的，自己算算速度和利润值不值得吧。

**Comment by liangxiwei** [comment]
https://github.com/liangxiwei/ore-mine-optimize-mac/issues/5
