### ISSUE TITLE
Scam Reported 诈骗，已经举报

### ISSUE THREAD

**Issue by lche059** [liangxiwei/ore-mine-optimize-mac#5]
https://github.com/okeyzero/egg_miner_rs/issues/1

**Comment by liangxiwei** [comment]
你爱用不用，别人挖降低你的奖励就到处黑人。我就是现在不开源，等币价降到10美元就把code push上来。我还有个linxu版本的在服务器已经挖上了。

看到这里的朋友建议你全部创建新的小号发个0.02就可以开挖了，还有必须quicknode节点。其他不想多说了。我TM辛辛苦苦熬了2个通宵搞出来的，我就想付出的汗水唤回一点价值，你自己挖看看一般人挖的fee是不是很大，我就相当于提高了你的速度，顺便把省下来的fee给我自己了。
